use crate::ast;
use crate::hir;

pub fn lower(program: &ast::Program) -> hir::Program {
    hir::Program { items: program.items.iter().map(item).collect() }
}
fn item(i:&ast::Item)->hir::Item{match i{ast::Item::Let{name,mutable,value}=>hir::Item::Let{name:name.clone(),mutable:*mutable,value:expr(value)},ast::Item::Fn{name,params,body}=>hir::Item::Fn{name:name.clone(),params:params.clone(),body:body.iter().map(stmt).collect()},ast::Item::Stmt(s)=>hir::Item::Stmt(stmt(s))}}
fn stmt(s:&ast::Stmt)->hir::Stmt{match s{ast::Stmt::Expr(e)=>hir::Stmt::Expr(expr(e)),ast::Stmt::Return(e)=>hir::Stmt::Return(e.as_ref().map(expr)),ast::Stmt::If{condition,then_branch,else_branch}=>hir::Stmt::If{condition:expr(condition),then_branch:then_branch.iter().map(stmt).collect(),else_branch:else_branch.iter().map(stmt).collect()},ast::Stmt::While{condition,body}=>hir::Stmt::While{condition:expr(condition),body:body.iter().map(stmt).collect()}}}
fn expr(e:&ast::Expr)->hir::Expr{match e{ast::Expr::Int(v)=>hir::Expr::Int(*v),ast::Expr::Float(v)=>hir::Expr::Float(*v),ast::Expr::Bool(v)=>hir::Expr::Bool(*v),ast::Expr::Str(v)=>hir::Expr::Str(v.clone()),ast::Expr::Ident(v)=>hir::Expr::Ident(v.clone()),ast::Expr::Unary{op,expr:e}=>hir::Expr::Unary{op:match op{ast::UnaryOp::Neg=>hir::UnaryOp::Neg,ast::UnaryOp::Not=>hir::UnaryOp::Not},expr:Box::new(expr(e))},ast::Expr::Binary{left,op,right}=>hir::Expr::Binary{left:Box::new(expr(left)),op:match op{ast::BinaryOp::Add=>hir::BinaryOp::Add,ast::BinaryOp::Sub=>hir::BinaryOp::Sub,ast::BinaryOp::Mul=>hir::BinaryOp::Mul,ast::BinaryOp::Div=>hir::BinaryOp::Div,ast::BinaryOp::Mod=>hir::BinaryOp::Mod,ast::BinaryOp::Eq=>hir::BinaryOp::Eq,ast::BinaryOp::Ne=>hir::BinaryOp::Ne,ast::BinaryOp::Lt=>hir::BinaryOp::Lt,ast::BinaryOp::Le=>hir::BinaryOp::Le,ast::BinaryOp::Gt=>hir::BinaryOp::Gt,ast::BinaryOp::Ge=>hir::BinaryOp::Ge,ast::BinaryOp::And=>hir::BinaryOp::And,ast::BinaryOp::Or=>hir::BinaryOp::Or},right:Box::new(expr(right))},ast::Expr::Call{callee,args}=>hir::Expr::Call{callee:Box::new(expr(callee)),args:args.iter().map(expr).collect()}}}
