use crate::ast::*;
use crate::lexer::{Token, TokenKind};
use crate::types::Type;

pub fn parse(tokens: &[Token]) -> Result<Program, String> { Parser { t: tokens, p: 0 }.program() }
struct Parser<'a> { t: &'a [Token], p: usize }
impl<'a> Parser<'a> {
 fn peek(&self)->&TokenKind { &self.t[self.p].kind }
 fn bump(&mut self)->TokenKind { let k=self.t[self.p].kind.clone(); self.p+=1;k }
 fn eat(&mut self,k:&TokenKind)->bool { if self.peek()==k{self.p+=1;true}else{false} }
 fn expect(&mut self,k:&TokenKind)->Result<(),String>{if self.eat(k){Ok(())}else{Err(format!("expected {:?}, found {:?}",k,self.peek()))}}
 fn program(mut self)->Result<Program,String>{let mut items=Vec::new();while *self.peek()!=TokenKind::Eof{items.push(self.item()?)}Ok(Program{items})}
 fn item(&mut self)->Result<Item,String>{match self.peek(){TokenKind::Let=>self.let_item().map(|x|match x{Stmt::Let{name,mutable,annotation,value}=>Item::Let{name,mutable,annotation,value},_=>unreachable!()}),TokenKind::Fn=>self.fn_item(),TokenKind::Struct=>self.struct_item(),_=>Ok(Item::Stmt(self.stmt()?))}}
 fn parse_type(&mut self)->Result<Type,String>{match self.bump(){TokenKind::Ident(name)=>match name.as_str(){"Int"=>Ok(Type::Int),"Float"=>Ok(Type::Float),"Bool"=>Ok(Type::Bool),"String"=>Ok(Type::String),"Unit"=>Ok(Type::Unit),"Array"=>{self.expect(&TokenKind::Lt)?;let inner=self.parse_type()?;self.expect(&TokenKind::Gt)?;Ok(Type::Array(Box::new(inner)))},_=>Err(format!("unknown type `{name}`"))},k=>Err(format!("expected type name, found {:?}",k))}}
 fn optional_type(&mut self)->Result<Option<Type>,String>{if self.eat(&TokenKind::Colon){Ok(Some(self.parse_type()?))}else{Ok(None)}}
 fn let_item(&mut self)->Result<Stmt,String>{self.bump();let mutable=self.eat(&TokenKind::Mut);let name=match self.bump(){TokenKind::Ident(x)=>x,_=>return Err("expected identifier after let".into())};let annotation=self.optional_type()?;self.expect(&TokenKind::Eq)?;let value=self.expr()?;self.expect(&TokenKind::Semicolon)?;Ok(Stmt::Let{name,mutable,annotation,value})}
 fn fn_item(&mut self)->Result<Item,String>{self.bump();let name=match self.bump(){TokenKind::Ident(x)=>x,_=>return Err("expected function name".into())};self.expect(&TokenKind::LParen)?;let mut params=Vec::new();if !self.eat(&TokenKind::RParen){loop{let pname=match self.bump(){TokenKind::Ident(x)=>x,_=>return Err("expected parameter".into())};let pty=self.optional_type()?;params.push(Param{name:pname,ty:pty});if self.eat(&TokenKind::RParen){break}self.expect(&TokenKind::Comma)?}}let return_type=if self.eat(&TokenKind::Arrow){Some(self.parse_type()?)}else{None};Ok(Item::Fn{name,params,return_type,body:self.block()?})}
 fn struct_item(&mut self)->Result<Item,String>{self.bump();let name=match self.bump(){TokenKind::Ident(x)=>x,_=>return Err("expected struct name".into())};self.expect(&TokenKind::LBrace)?;let mut fields=Vec::new();if !self.eat(&TokenKind::RBrace){loop{let fname=match self.bump(){TokenKind::Ident(x)=>x,_=>return Err("expected field name".into())};self.expect(&TokenKind::Colon)?;let ty=self.parse_type()?;fields.push(Field{name:fname,ty});if self.eat(&TokenKind::RBrace){break}self.expect(&TokenKind::Comma)?;}}Ok(Item::Struct{name,fields})}
 fn block(&mut self)->Result<Vec<Stmt>,String>{self.expect(&TokenKind::LBrace)?;let mut v=Vec::new();while !self.eat(&TokenKind::RBrace){if *self.peek()==TokenKind::Eof{return Err("unterminated block".into())}v.push(self.stmt()?)}Ok(v)}
 fn stmt(&mut self)->Result<Stmt,String>{match self.peek(){
  TokenKind::Let=>self.let_item(),
  TokenKind::Return=>{self.bump();let e=if self.eat(&TokenKind::Semicolon){None}else{let x=self.expr()?;self.expect(&TokenKind::Semicolon)?;Some(x)};Ok(Stmt::Return(e))},
  TokenKind::If=>{self.bump();let c=self.expr()?;let a=self.block()?;let b=if self.eat(&TokenKind::Else){self.block()?}else{Vec::new()};Ok(Stmt::If{condition:c,then_branch:a,else_branch:b})},
  TokenKind::While=>{self.bump();let c=self.expr()?;Ok(Stmt::While{condition:c,body:self.block()?})},
  TokenKind::Loop=>{self.bump();Ok(Stmt::Loop{body:self.block()?})},
  TokenKind::Break=>{self.bump();self.expect(&TokenKind::Semicolon)?;Ok(Stmt::Break)},
  TokenKind::Continue=>{self.bump();self.expect(&TokenKind::Semicolon)?;Ok(Stmt::Continue)},
  TokenKind::For=>{self.bump();let name=match self.bump(){TokenKind::Ident(x)=>x,_=>return Err("expected loop variable after for".into())};self.expect(&TokenKind::In)?;let iterable=self.expr()?;let body=self.block()?;Ok(Stmt::For{name,iterable,body})},
  _=>{let target=self.expr()?;if self.eat(&TokenKind::Eq){let value=self.expr()?;self.expect(&TokenKind::Semicolon)?;Ok(Stmt::Assign{target,value})}else{self.expect(&TokenKind::Semicolon)?;Ok(Stmt::Expr(target))}}
 }}
 fn expr(&mut self)->Result<Expr,String>{self.binary(0)}
 fn prec(k:&TokenKind)->Option<u8>{Some(match k{TokenKind::OrOr=>1,TokenKind::AndAnd=>2,TokenKind::EqEq|TokenKind::BangEq=>3,TokenKind::Lt|TokenKind::Le|TokenKind::Gt|TokenKind::Ge=>4,TokenKind::Plus|TokenKind::Minus=>5,TokenKind::Star|TokenKind::Slash|TokenKind::Percent=>6,_=>return None})}
 fn binary(&mut self,min:u8)->Result<Expr,String>{let mut left=self.unary()?;loop{let Some(p)=Self::prec(self.peek())else{break};if p<min{break}let op=match self.bump(){TokenKind::Plus=>BinaryOp::Add,TokenKind::Minus=>BinaryOp::Sub,TokenKind::Star=>BinaryOp::Mul,TokenKind::Slash=>BinaryOp::Div,TokenKind::Percent=>BinaryOp::Mod,TokenKind::EqEq=>BinaryOp::Eq,TokenKind::BangEq=>BinaryOp::Ne,TokenKind::Lt=>BinaryOp::Lt,TokenKind::Le=>BinaryOp::Le,TokenKind::Gt=>BinaryOp::Gt,TokenKind::Ge=>BinaryOp::Ge,TokenKind::AndAnd=>BinaryOp::And,TokenKind::OrOr=>BinaryOp::Or,_=>unreachable!()};let right=self.binary(p+1)?;left=Expr::Binary{left:Box::new(left),op,right:Box::new(right)}}Ok(left)}
 fn unary(&mut self)->Result<Expr,String>{match self.peek(){TokenKind::Minus=>{self.bump();Ok(Expr::Unary{op:UnaryOp::Neg,expr:Box::new(self.unary()?)})},TokenKind::Bang=>{self.bump();Ok(Expr::Unary{op:UnaryOp::Not,expr:Box::new(self.unary()?)})},_=>self.postfix()}}
 fn postfix(&mut self)->Result<Expr,String>{let mut e=self.primary()?;loop{if self.eat(&TokenKind::LParen){let mut args=Vec::new();if !self.eat(&TokenKind::RParen){loop{args.push(self.expr()?);if self.eat(&TokenKind::RParen){break}self.expect(&TokenKind::Comma)?}}e=Expr::Call{callee:Box::new(e),args}}else if self.eat(&TokenKind::LBracket){let index=self.expr()?;self.expect(&TokenKind::RBracket)?;e=Expr::Index{target:Box::new(e),index:Box::new(index)}}else if self.peek()==&TokenKind::Dot{}else{break}if self.peek()==&TokenKind::Ident(String::new()){} }Ok(e)}
 fn primary(&mut self)->Result<Expr,String>{match self.bump(){TokenKind::Int(x)=>Ok(Expr::Int(x)),TokenKind::Float(x)=>Ok(Expr::Float(x)),TokenKind::Bool(x)=>Ok(Expr::Bool(x)),TokenKind::True=>Ok(Expr::Bool(true)),TokenKind::False=>Ok(Expr::Bool(false)),TokenKind::Str(x)=>Ok(Expr::Str(x)),TokenKind::Ident(x)=>{if self.eat(&TokenKind::LBrace){let mut fields=Vec::new();if !self.eat(&TokenKind::RBrace){loop{let fname=match self.bump(){TokenKind::Ident(n)=>n,_=>return Err("expected struct field name".into())};self.expect(&TokenKind::Colon)?;let value=self.expr()?;fields.push((fname,value));if self.eat(&TokenKind::RBrace){break}self.expect(&TokenKind::Comma)?}}Ok(Expr::StructInit{name:x,fields})}else{Ok(Expr::Ident(x))}},TokenKind::LBracket=>{let mut values=Vec::new();if !self.eat(&TokenKind::RBracket){loop{values.push(self.expr()?);if self.eat(&TokenKind::RBracket){break}self.expect(&TokenKind::Comma)?}}Ok(Expr::Array(values))},TokenKind::LParen=>{let x=self.expr()?;self.expect(&TokenKind::RParen)?;Ok(x)},k=>Err(format!("unexpected token {:?}",k))}}
}
