use crate::ast::*;
use crate::types::Type;
use std::collections::HashMap;

#[derive(Clone, Debug)] pub struct TypedProgram { pub items:Vec<TypedItem> }
#[derive(Clone, Debug)] pub enum TypedItem { Let{name:String,mutable:bool,annotation:Option<Type>,value:TypedExpr}, Fn{name:String,params:Vec<Param>,return_type:Type,body:Vec<TypedStmt>}, Stmt(TypedStmt) }
#[derive(Clone, Debug)] pub enum TypedStmt { Expr(TypedExpr), Let{name:String,mutable:bool,annotation:Option<Type>,value:TypedExpr}, Assign{target:TypedExpr,value:TypedExpr}, Return(Option<TypedExpr>), If{condition:TypedExpr,then_branch:Vec<TypedStmt>,else_branch:Vec<TypedStmt>}, While{condition:TypedExpr,body:Vec<TypedStmt>}, For{name:String,iterable:TypedExpr,body:Vec<TypedStmt>}, Loop{body:Vec<TypedStmt>}, Break, Continue }
#[derive(Clone, Debug)] pub struct TypedExpr { pub expr: Expr, pub ty: Type }

#[derive(Default)] pub struct TypeChecker { scopes:Vec<HashMap<String,Type>>, mutability:Vec<HashMap<String,bool>>, functions:HashMap<String,(Vec<Type>,Type)>, loop_depth:usize, current_return:Option<Type> }
impl TypeChecker {
 pub fn check(program:&Program)->Result<TypedProgram,Vec<String>>{let mut c=Self::default();c.push_scope();for i in &program.items{if let Item::Fn{name,params,return_type,..}=i{c.functions.insert(name.clone(),(params.iter().map(|p|p.ty.clone().unwrap_or(Type::Unknown)).collect(),return_type.clone().unwrap_or(Type::Unknown)));}}let mut es=Vec::new();let mut out=Vec::new();for i in &program.items{match c.item(i){Ok(x)=>out.push(x),Err(e)=>es.extend(e)}}c.pop_scope();if es.is_empty(){Ok(TypedProgram{items:out})}else{Err(es)}}
 fn push_scope(&mut self){self.scopes.push(HashMap::new());self.mutability.push(HashMap::new())} fn pop_scope(&mut self){self.scopes.pop();self.mutability.pop();}
 fn define(&mut self,n:&str,t:Type,m:bool)->Result<(),String>{let s=self.scopes.last_mut().unwrap();if s.contains_key(n){return Err(format!("duplicate definition of `{n}`"))}s.insert(n.into(),t);self.mutability.last_mut().unwrap().insert(n.into(),m);Ok(())}
 fn lookup(&self,n:&str)->Option<Type>{self.scopes.iter().rev().find_map(|s|s.get(n).cloned())} fn is_mutable(&self,n:&str)->bool{self.mutability.iter().rev().find_map(|s|s.get(n).copied()).unwrap_or(false)}
 fn bind_decl(&self,annotation:&Option<Type>,actual:&Type,name:&str)->Result<Type,String>{match annotation{Some(expected) if !expected.compatible_with(actual)=>Err(format!("type annotation for `{name}` expects {}, found {}",expected,actual)),Some(expected)=>Ok(expected.clone()),None=>Ok(actual.clone())}}
 fn item(&mut self,i:&Item)->Result<TypedItem,Vec<String>>{match i{Item::Let{name,mutable,annotation,value}=>self.expr(value).and_then(|v|{let t=self.bind_decl(annotation,&v.ty,name)?;self.define(name,t,*mutable)?;Ok(TypedItem::Let{name:name.clone(),mutable:*mutable,annotation:annotation.clone(),value:v})}).map_err(|e|vec![e]),Item::Fn{name,params,return_type,body}=>{self.define(name,Type::Unknown,false).map_err(|e|vec![e])?;self.push_scope();for p in params{self.define(&p.name,p.ty.clone().unwrap_or(Type::Unknown),true).map_err(|e|vec![e])?}let old=self.current_return.take();self.current_return=return_type.clone();let mut b=Vec::new();let mut es=Vec::new();for s in body{match self.stmt(s){Ok(x)=>b.push(x),Err(x)=>es.extend(x)}}let inferred=self.current_return.clone().unwrap_or(Type::Unit);self.current_return=old;self.pop_scope();if es.is_empty(){self.functions.insert(name.clone(),(params.iter().map(|p|p.ty.clone().unwrap_or(Type::Unknown)).collect(),inferred.clone()));Ok(TypedItem::Fn{name:name.clone(),params:params.clone(),return_type:inferred,body:b})}else{Err(es)}},Item::Stmt(s)=>self.stmt(s).map(TypedItem::Stmt)}}
 fn stmt(&mut self,s:&Stmt)->Result<TypedStmt,Vec<String>>{match s{Stmt::Expr(e)=>self.expr(e).map(TypedStmt::Expr).map_err(|e|vec![e]),Stmt::Let{name,mutable,annotation,value}=>self.expr(value).and_then(|v|{let t=self.bind_decl(annotation,&v.ty,name)?;self.define(name,t,*mutable)?;Ok(TypedStmt::Let{name:name.clone(),mutable:*mutable,annotation:annotation.clone(),value:v})}).map_err(|e|vec![e]),Stmt::Assign{target,value}=>{let t=self.expr(target).map_err(|e|vec![e])?;let v=self.expr(value).map_err(|e|vec![e])?;match &t.expr{Expr::Ident(n)=>if !self.is_mutable(n){return Err(vec![format!("cannot assign to immutable variable `{n}`")])},Expr::Index{..}=>{},_=>return Err(vec!["assignment target must be a variable or indexed collection".into()])}if !t.ty.compatible_with(&v.ty){return Err(vec![format!("cannot assign {} to {}",v.ty,t.ty)])}Ok(TypedStmt::Assign{target:t,value:v})},Stmt::Return(e)=>{let value=e.as_ref().map(|x|self.expr(x)).transpose().map_err(|e|vec![e])?;let actual=value.as_ref().map(|x|x.ty.clone()).unwrap_or(Type::Unit);match &mut self.current_return{Some(expected) if *expected!=Type::Unknown=>{if !expected.compatible_with(&actual){return Err(vec![format!("function must return {}, found {}",expected,actual)])}},Some(expected)=>*expected=actual,None=>self.current_return=Some(actual)}Ok(TypedStmt::Return(value))},Stmt::If{condition,then_branch,else_branch}=>{let c=self.expr(condition).map_err(|e|vec![e])?;if c.ty!=Type::Bool&&c.ty!=Type::Unknown{return Err(vec![format!("if condition must be Bool, found {}",c.ty)])}self.push_scope();let t=self.block(then_branch);self.pop_scope();let t=t?;self.push_scope();let e=self.block(else_branch);self.pop_scope();Ok(TypedStmt::If{condition:c,then_branch:t,else_branch:e?})},Stmt::While{condition,body}=>{let c=self.expr(condition).map_err(|e|vec![e])?;if c.ty!=Type::Bool&&c.ty!=Type::Unknown{return Err(vec![format!("while condition must be Bool, found {}",c.ty)])}self.push_scope();self.loop_depth+=1;let b=self.block(body);self.loop_depth-=1;self.pop_scope();Ok(TypedStmt::While{condition:c,body:b?})},Stmt::For{name,iterable,body}=>{let it=self.expr(iterable).map_err(|e|vec![e])?;let inner=match it.ty{Type::Array(x)=>*x,Type::String=>Type::String,_=>return Err(vec![format!("for-in requires an Array or String, found {}",it.ty)])};self.push_scope();self.define(name,&inner,false).map_err(|e|vec![e])?;self.loop_depth+=1;let b=self.block(body);self.loop_depth-=1;self.pop_scope();Ok(TypedStmt::For{name:name.clone(),iterable:it,body:b?})},Stmt::Loop{body}=>{self.push_scope();self.loop_depth+=1;let b=self.block(body);self.loop_depth-=1;self.pop_scope();Ok(TypedStmt::Loop{body:b?})},Stmt::Break=>if self.loop_depth==0{Err(vec!["break is only valid inside a loop".into()])}else{Ok(TypedStmt::Break)},Stmt::Continue=>if self.loop_depth==0{Err(vec!["continue is only valid inside a loop".into()])}else{Ok(TypedStmt::Continue)}}}
 fn block(&mut self,b:&[Stmt])->Result<Vec<TypedStmt>,Vec<String>>{let mut o=Vec::new();let mut e=Vec::new();for s in b{match self.stmt(s){Ok(x)=>o.push(x),Err(x)=>e.extend(x)}}if e.is_empty(){Ok(o)}else{Err(e)}}
 fn expr(&mut self,e:&Expr)->Result<TypedExpr,String>{let t=match e{Expr::Int(_)=>Type::Int,Expr::Float(_)=>Type::Float,Expr::Bool(_)=>Type::Bool,Expr::Str(_)=>Type::String,Expr::Array(v)=>{let mut inner=Type::Unknown;for x in v{let z=self.expr(x)?;if inner==Type::Unknown{inner=z.ty}else if !inner.compatible_with(&z.ty){return Err(format!("array elements must have compatible types, found {} and {}",inner,z.ty))}}Type::Array(Box::new(inner))},Expr::Ident(n)=>self.lookup(n).ok_or_else(||format!("unknown identifier `{n}`"))?,Expr::Index{target,index}=>{let target=self.expr(target)?;let index=self.expr(index)?;if index.ty!=Type::Int&&index.ty!=Type::Unknown{return Err(format!("collection index must be Int, found {}",index.ty))}match target.ty{Type::Array(inner)=>*inner,Type::String=>Type::String,_=>return Err(format!("cannot index {}",target.ty))}},Expr::Unary{op,expr}=>{let x=self.expr(expr)?;match op{UnaryOp::Neg if x.ty.is_numeric()=>x.ty,UnaryOp::Not if x.ty==Type::Bool||x.ty==Type::Unknown=>Type::Bool,UnaryOp::Neg=>return Err(format!("cannot negate {}",x.ty)),UnaryOp::Not=>return Err(format!("cannot apply ! to {}",x.ty))}},Expr::Binary{left,op,right}=>{let a=self.expr(left)?;let b=self.expr(right)?;match op{BinaryOp::Add|BinaryOp::Sub|BinaryOp::Mul|BinaryOp::Div|BinaryOp::Mod=>if a.ty.is_numeric()&&b.ty.is_numeric(){Type::common_numeric(&a.ty,&b.ty).unwrap()}else if *op==BinaryOp::Add&&a.ty==Type::String&&b.ty==Type::String{Type::String}else if *op==BinaryOp::Add&&matches!((&a.ty,&b.ty),(Type::Array(_),Type::Array(_)))&&a.ty.compatible_with(&b.ty){a.ty.clone()}else{return Err(format!("invalid operands: {} and {}",a.ty,b.ty))},BinaryOp::Eq|BinaryOp::Ne=>if a.ty.compatible_with(&b.ty){Type::Bool}else{return Err(format!("cannot compare {} and {}",a.ty,b.ty))},BinaryOp::Lt|BinaryOp::Le|BinaryOp::Gt|BinaryOp::Ge=>if a.ty.is_numeric()&&b.ty.is_numeric(){Type::Bool}else{return Err("ordering requires numeric operands".into())},BinaryOp::And|BinaryOp::Or=>if(a.ty==Type::Bool||a.ty==Type::Unknown)&&(b.ty==Type::Bool||b.ty==Type::Unknown){Type::Bool}else{return Err("logical operators require Bool operands".into())}},Expr::Call{callee,args}=>{let n=match callee.as_ref(){Expr::Ident(n)=>n,_=>return Err("call target must currently be an identifier".into())};if n=="print"{for a in args{self.expr(a)?}return Ok(TypedExpr{expr:e.clone(),ty:Type::Unit})}let(ps,r)=self.functions.get(n).cloned().ok_or_else(||format!("unknown function `{n}`"))?;if ps.len()!=args.len(){return Err(format!("function `{n}` expects {} arguments, got {}",ps.len(),args.len()))}for (idx,a) in args.iter().enumerate(){let at=self.expr(a)?.ty;if ps[idx]!=Type::Unknown&&!ps[idx].compatible_with(&at){return Err(format!("argument {} to `{}` expects {}, found {}",idx+1,n,ps[idx],at))}}r}};Ok(TypedExpr{expr:e.clone(),ty:t})}
}
